import { Result } from '@/src/result';
import { ResultAsync } from '@/src/resultAsync';

describe('ResultAsync', () => {
  describe('combineInOrder', () => {
    it('succeeds with one successful ResultAsync', async () => {
      const sut = await ResultAsync.combineInOrder({
        success: ResultAsync.success('âœ…'),
      }).toPromise();

      expect(sut).toSucceedWith({
        success: 'âœ…',
      });
    });

    it('succeeds with two successful ResultAsync', async () => {
      const sut = await ResultAsync.combineInOrder({
        first: ResultAsync.success('âœ…'),
        second: ResultAsync.success('âœ…'),
      }).toPromise();

      expect(sut).toSucceedWith({
        first: 'âœ…',
        second: 'âœ…',
      });
    });

    it('fails with one failed ResultAsync', async () => {
      const sut = await ResultAsync.combineInOrder({
        failure: ResultAsync.failure('ğŸ’¥'),
      }).toPromise();

      expect(sut).toFailWith('ğŸ’¥');
    });

    it('fails with one successful and one failed ResultAsync', async () => {
      const sut = await ResultAsync.combineInOrder({
        success: ResultAsync.success('âœ…'),
        failure: ResultAsync.failure('ğŸ’¥'),
      }).toPromise();

      expect(sut).toFailWith('ğŸ’¥');
    });

    it('succeeds with one successful Result', async () => {
      const sut = await ResultAsync.combineInOrder({
        success: Result.success('âœ…'),
      }).toPromise();

      expect(sut).toSucceedWith({
        success: 'âœ…',
      });
    });

    it('succeeds with two successful Results', async () => {
      const sut = await ResultAsync.combineInOrder({
        first: Result.success('âœ…'),
        second: Result.success('âœ…'),
      }).toPromise();

      expect(sut).toSucceedWith({
        first: 'âœ…',
        second: 'âœ…',
      });
    });

    it('fails with one failed Result', async () => {
      const sut = await ResultAsync.combineInOrder({
        failure: Result.failure('ğŸ’¥'),
      }).toPromise();

      expect(sut).toFailWith('ğŸ’¥');
    });

    it('fails with one successful and one failed Result', async () => {
      const sut = await ResultAsync.combineInOrder({
        success: Result.success('âœ…'),
        failure: Result.failure('ğŸ’¥'),
      }).toPromise();

      expect(sut).toFailWith('ğŸ’¥');
    });

    it('fails with mixed types when one fails', async () => {
      const sut = await ResultAsync.combineInOrder({
        sut: Result.success('âœ…'),
        sutAsync: ResultAsync.failure('ğŸ’¥'),
      }).toPromise();

      expect(sut).toFailWith('ğŸ’¥');
    });

    it('concatenates failures', async () => {
      const sut = await ResultAsync.combineInOrder({
        sut: Result.failure('ğŸ’¥'),
        sutAsync: ResultAsync.failure('ğŸ’¥'),
      }).toPromise();

      expect(sut).toFailWith('ğŸ’¥, ğŸ’¥');
    });
  });
});
